 
 SELECT CONTINENT, COUNTRY, ISLAND, SUM(TOTAL_DEATHS) AS ISLAND_DEATH 
  FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DIPTESH_KUNDU
  WHERE ISLAND IS NOT NULL
  GROUP BY CONTINENT, COUNTRY, ISLAND
 ORDER BY SUM(TOTAL_DEATHS) DESC